[package]
name = "morse-sigusr-ipc"
version = "0.1.0"
authors = ["Daniel Schaefer <git@danielschaefer.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.1.13"
libc = "0.2.69"
